simu:
  dataDir: Straat_data
  tInit: 200
  nSimu: 20
  dtData: 0.5
  tEnd: 300

sample:
  inSize: 1
  outStep: 5
  inStep: 1

data:
  outType: solution
  dataFile: dataset_96x64_Ra5e6_dt0_5_sol.h5
  trainRatio: 0.75
  seed: null
  batchSize: 32  # local batch size
  xStep: 1
  yStep: 1
  
model:
  da: 4
  du: 4
  dv: 64
  kX: 16
  kY: 16
  nLayers: 8
  forceFFT: true
  bias: false
  scaling_layers: 4
  use_prechannel_mlp: true
  channel_mlp_expansion: 4
  use_fno_skip_connection: false
  fno_skip_type: soft-gating
  use_postfnochannel_mlp: false
  channel_mlp_skip_type: 'soft-gating'
  use_dse: false
  get_subdomain_output: False              # set to true only for inference
  iXBeg: 0
  iYBeg: 0
  iXEnd: 96
  iYEnd: 64

optim:
  name: adamw
  lr: 1.0e-4
  weight_decay: 1.0e-4

lr_scheduler:
  scheduler: CosAnnealingLR
  T_max: 1000

parallel_strategy:
  ddp: true
  gpus_per_node: 4

train:
  trainDir: straat_paper_dt0_5_sol
  nEpochs: 500
  checkpoint: model_epochs500.pt
  lossesFile: losses.txt
  saveEvery: 50
  savePermanent: true
  noTensorboard: false
  logPrint: false
  data_aug: false
  model_class: CFNO
  ndim: 2

eval:
  iSimu: 15
  imgExt: png
  evalDir: eval
  tSteps: 60
  batchsize: 10
  model_dt: 0.5
  sample: random
  compile: false
 