simu:
  dataDir: simuData
  tInit: 100
  nSimu: 10
  dtData: 0.001
  tEnd: 100

sample:
  inSize: 1
  outStep: 1
  inStep: 500

data:
  outType: update
  outScaling: 1000
  dataFile: dataset_dt1e-3_update.h5
  trainRatio: 0.8
  seed: null
  batchSize: 20
  xStep: 1
  yStep: 1
  use_domainSampling: true
  use_fixedPatchSize: false        # fixed domain with overlapping
  use_orderedSampling: false       # fixed domain w/o overlapping 
  pad_to_fullGrid: false
  use_fixedPatch_startIdx: true
  nPatch_per_sample: 100
  use_minLimit: true
  padding : [1,1,1,1]
  # slices: []
  # patch_startIdx: []

model:
  da: 4
  du: 4
  dv: 16
  kX: 12
  kY: 12
  nLayers: 2
  forceFFT: true
  bias: false
  use_prechannel_mlp: true
  channel_mlp_expansion: 4
  use_fno_skip_connection: false
  fno_skip_type: soft-gating
  use_postfnochannel_mlp: false
  channel_mlp_skip_type: 'soft-gating'
  get_subdomain_output: false               # set to true only for inference
  iXBeg: 5
  iYBeg: 12
  iXEnd: 30
  iYEnd: 60

optim:
  name: adam
  lr: 0.001
  weight_decay: 1.0e-5

lr_scheduler:
  scheduler: CosAnnealingLR
  T_max: 50000

train:
  trainDir: training_dt1e-3_update_fft_test
  nEpochs: 20000
  checkpoint: model.pt
  lossesFile: losses.txt
  saveEvery: 100
  savePermanent: false
  noTensorboard: false
  logPrint: false

eval:
  iSimu: 8
  imgExt: png
  evalDir: evalDir