simu:
  dataDir: simuData
  tInit: 100
  nSimu: 10
  dtData: 0.001
  tEnd: 100

sample:
  inSize: 1
  outStep: 1
  inStep: 500

data:
  outType: update
  outScaling: 1000
  dataFile: dataset_dt1e-3_update.h5
  trainRatio: 0.8
  seed: null
  batchSize: 20
  xStep: 1
  yStep: 1
  use_domain_sampling: true
  nPatch_per_sample: 100
  use_min_limit: false
  padding : [1,1,1,1]

model:
  da: 4
  du: 4
  dv: 16
  kX: 12
  kY: 12
  nLayers: 2
  forceFFT: true
  bias: false
  use_prechannel_mlp: true
  channel_mlp_expansion: 4
  use_fno_skip_connection: false
  fno_skip_type: soft-gating
  use_postfnochannel_mlp: false
  channel_mlp_skip_type: 'soft-gating'
  use_prechannel_mlp: true
  channel_mlp_expansion: 4
  use_fno_skip_connection: false
  fno_skip_type: soft-gating
  use_postfnochannel_mlp: false
  channel_mlp_skip_type: 'soft-gating'

optim:
  name: adam
  lr: 0.001
  weight_decay: 1.0e-5

lr_scheduler:
  scheduler: CosAnnealingLR
  T_max: 50000

train:
  trainDir: training_dt1e-3_update_fft_run26
  nEpochs: 20000
  checkpoint: model.pt
  lossesFile: losses.txt
  saveEvery: 100
  savePermanent: false
  noTensorboard: false
  logPrint: false

eval:
  iSimu: 8
  imgExt: png
  evalDir: evalDir